### ISSUE TITLE
🚀 Feature: verify if local directory is a `git` repository

### ISSUE THREAD

**Issue by RickyC0626** [RickyC0626/timestream#14]
## Expected Behavior

- If directory is a repository, show "Yes"
- If directory is not a repository, show "No"

## Tasks

- [x] Setup Go API server using `gin-gonic/gin`
- [ ] Setup `go-git` package
- [ ] Select local directory
- [ ] Verify if local directory is a git repo
